### ISSUE TITLE
Incorrect Tokenizer Result

### ISSUE THREAD

**Issue by ty2** [timtadh/lexmachine#20]
My Code:
```go
lexer := lexmachine.NewLexer()
lexer.Add([]byte(`(\"\"\"\s)(\\.|[^\\\"\"\"])*(\s\"\"\")`), token("stringBlock"))

lexer.Add([]byte(`\"(\\.|[^\\\"\n])*\"`), token("string"))

lexer.Add([]byte("( |\t|\n|\r|,)"), skip)

lexer.Compile()

s, err := lexer.Scanner([]byte(`""""""`))

if err != nil {
	return nil, err
}

for tok, err, eof := s.Next(); !eof; tok, err, eof = s.Next() {
	if err != nil{
		log.Fatal(err)
	}
	token := tok.(*Token)
	fmt.Printf("%-7v | %-10v | %v:%v-%v:%v\n",
		token.Type,
		token.Value,
		token.StartLine,
		token.StartColumn,
		token.EndLine,
		token.EndColumn)
}

```

Output:
```
string  | ""         | 1:1-1:2
string  | ""         | 1:4-1:5
```

Expect:
```
string  | ""         | 1:1-1:2
string  | ""         | 1:3-1:4
string  | ""         | 1:5-1:6
```

If I comment this line, everything as expect:
```go
// lexer.Add([]byte(`(\"\"\"\s)(\\.|[^\\\"\"\"])*(\s\"\"\")`), token("stringBlock"))
```

This is a bug, limitation or my mistake?

Thanks.

**Comment by timtadh** [comment]
@ty2 I am going to take a look tomorrow. Could be related to my fix in #19 . You could try v0.2.0 (in the meantime) and see if it works there. My initial scan of your regex says it "should work" so probably a bug I introduced.

**Comment by ty2** [comment]
Thanks. I had tried v0.2.0

CompileNFA() Result:
```
string  | ""         | 1:1-1:2
string  | ""         | 1:4-1:5
```

Compile() Result:
```
string  | ""         | 1:1-1:2
2018/02/23 19:30:43 Lexer error: could not match text starting at 1:4 failing at 1:6.
        unmatched text: "\"\"\""
```

**Comment by ty2** [comment]
Another Example:
lexmachine v0.2.0

```go
lexer.Scanner([]byte(`"""
  str
  1231"""`))
```

CompileNFA() Result:
```
string  | ""         | 1:1-1:2
string  | ""         | 3:7-3:8
```

Compile() Result:
```
string  | ""         | 1:1-1:2
2018/02/23 20:01:30 Lexer error: could not match text starting at 3:7 failing at 3:9.
        unmatched text: "\"\"\""
exit status 1
```

**Comment by timtadh** [comment]
taking a look now

**Comment by timtadh** [comment]
@ty2 Ok I think I found the problem, it is in your regex:

Your regex:

1. `(\"\"\"\s)(\\.|[^\\\"\"\"])*(\s\"\"\")`
2. reduces to: `"""\s(\\.|[^\\"])*\s"""`

This coverts to the following DFA (with the addition of the `space` rule):

![ty2-dfa](https://user-images.githubusercontent.com/38620/36600531-656ac376-1867-11e8-9fca-12020a30b12d.png)

The correct regex is: `"""(\\.|[^\\"])*"""`

![fixed-dfa](https://user-images.githubusercontent.com/38620/36600578-85c15504-1867-11e8-9e24-301c97aba600.png)

Note the extra states in the DFA for your regex. They are there because you have `\s` which forces a space between the quote markers and whatever is in the quotes. `\s` is a [special range matching character](https://github.com/timtadh/lexmachine#built-in-character-classes) in lexmachine that matches space like characters.

**Comment by ty2** [comment]
If I use this regex `"""(\\.|[^\\"])*"""` instead, I still get a incorrect tokens.

```go
// input
lexer.Scanner([]byte(`""""
	""""`))
```

```
string  | ""           | 1:1-1:2
string  | ""           | 2:2-2:3
```

Actually, I want match a text like that:

```
"""
"""
```
```
"""
hello
"""
```
the first line: start with 3 double quotes and accept whitespace and tab
middle (optional): any text
the last line: accept whitespace and tab and end with 3 double quotes

**Comment by timtadh** [comment]
@ty2 see 03614ddbda19efa07cc3114780994fa9dddb067a . I can't reproduce what you are seeing. Maybe you can paste your actual code? At the moment I am inclined to think you have a typo.

**Comment by ty2** [comment]
@timtadh https://gist.github.com/ty2/cf33ef6cc215d315ee75775241556d41

**Comment by timtadh** [comment]
@ty2 you had a bug and I had bug. You had 4 quotes in your test strings (this should have matched 2 single strings a space and 2 single strings). However, a bug in my code caused it to fail. That is fixed in #21 . Please test.

**Comment by ty2** [comment]
I had test it #21 , it is fixed. Thanks. 😘
